[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "qtegui"
version = "0.1.0"
description = "QTE GUI/CLI driver"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
qtegui = "qtegui.cli:main"
